config/routes.rb
Rails.application.routes.draw do
  get 'students/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "students#index"
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path,notice: "Student is Created"
    else
      render :new
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to @student, notice: 'Student was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to root_path, notice: 'Student was successfully deleted.'
  end

  private
  def student_params
    params.require(:student).permit(:name,:number,:city,:descriptions)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<%= form_for @student do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </p>
 
  <p>
    <%= f.label :descriptions %><br>
    <%= f.text_area :descriptions %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', root_path%>

app/views/students/index.html.erb
<h1><strong>My Students Platform</strong></h1>
<hr>
<h3>List of the Students</h3>

<% @students.each do |student|%>
  <li>
   <%= link_to student.name ,student_path(student)%> | <%= link_to 'Update student',edit_student_path(student)%>| <%= button_to 'Delete Student',student_path(student), method: :delete, data: { confirm: 'Are you sure?' }%>
    <br>
  </li>
<%end%>

<%= link_to "Create Student", new_student_path%>

app/views/students/new.html.erb
<%= form_for @student do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </p>
 
  <p>
    <%= f.label :descriptions %><br>
    <%= f.text_area :descriptions %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/students/show.html.erb
<h2>Students Detail</h2>

<div>
  <ul>
    <li>
      <strong>Name</strong>
      <%= @student.name %>
    </li>

    <li>
      <strong>Number</strong>
      <%= @student.number %>
    </li>
    
    <li>
      <strong>City</strong>
      <%= @student.city %>
    </li>

    <li>
      <strong>Descriptions</strong>
      <%= @student.descriptions %>
    </li>
  </ul>
</div>
<%= link_to 'Back', root_path%>